name: Node.js GitHub Action

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    strategy:
     matrix:
      os: [ubuntu-latest, windows-letest]
      version: [14, 16, 18]
    runs-on: ${{matrix.os}} 
 
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{matrix.version}}

    - name: Install dependencies
      run: npm install
